[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "surgicalai"
version = "0.1.0"
description = "Research prototype for surgical AI utilities"
readme = "README.md"
requires-python = ">=3.10"
license = {file = "LICENSE"}
authors = [{name = "Surgical AI Team"}]

[project.scripts]
surgicalai = "surgicalai_cli:app"

[tool.ruff]
line-length = 88
target-version = "py310"

[tool.pytest.ini_options]
addopts = "-q"
testpaths = ["tests"]
