[project]
name = "surgicalai"
version = "0.1.0"
description = "MVP surgical AI pipeline"
readme = "README.md"
authors = [{name="OpenAI", email="example@example.com"}]
requires-python = ">=3.10"

[project.scripts]
surgicalai = "surgicalai.cli:app"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
