analyze:
  gradcam_threshold: 0.6
  n_views: 8
plan:
  arc_multiplier: 3.5
  tension_angle_deg: [30, 45]
validate:
  danger_margin_mm: 5.0
llm:
  enabled: false
  model: "gpt-4o"
  max_tokens: 700
  temperature: 0.2
  timeout_s: 30
  redact_phi: true
