analyze:
  gradcam_threshold: 0.6
  n_views: 8
plan:
  arc_multiplier: 3.5
  tension_angle_deg: [30, 45]
validate:
  danger_margin_mm: 5.0
llm:
  enabled: false
  model: "gpt-4o"
  max_tokens: 700
  temperature: 0.2
  timeout_s: 30
  redact_phi: true
train:
  img_size: 256
  batch_size: 32
  num_workers: 4
  max_epochs: 30
  lr: 0.0003
  weight_decay: 0.0001
  early_stop_patience: 5
  class_names:
    - benign
    - melanoma
data:
  source: folder
  root: data/lesions
  csv: data/lesions/labels.csv
  db_dsn: postgresql+psycopg2://user:pass@host/dbname
export:
  to_onnx: true
  to_torchscript: true
