name: ci
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: python -m pip install --upgrade pip
      - run: pip install -e ".[dev,demo]"
      - run: ruff check .
      - run: black --check .
      - run: mypy surgicalai
      - run: pytest -q
      - run: make demo
      - uses: actions/upload-artifact@v4
        with:
          name: demo-outputs
          path: runs/demo/**
