name: publish-nuget
on:
  push:
    tags: ['v*.*.*']
permissions:
  contents: read
  packages: write
jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Export OpenAPI
        run: python scripts/export_openapi.py

      - name: Generate C# client from OpenAPI
        uses: openapi-generators/openapi-generator-action@v1
        with:
          generator: csharp-netcore
          openapi-file: ./docs/openapi.json
          command-args: -o clients/csharp -p packageName=SurgicalAI.Client

      - name: Pack
        working-directory: clients/csharp
        run: dotnet pack -c Release -o out

      - name: Publish to GitHub Packages (NuGet)
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: dotnet nuget push clients/csharp/out/*.nupkg --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --api-key $NUGET_AUTH_TOKEN
